<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 3 Subclassification and Matching | Econometrics of Policy Evaluation</title>
  <meta name="description" content="ECON 474 R-lab notes" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content=" 3 Subclassification and Matching | Econometrics of Policy Evaluation" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://guerramarcelino.github.io/Econ474/474-Rlabs/" />
  
  <meta property="og:description" content="ECON 474 R-lab notes" />
  <meta name="github-repo" content="guerramarcelino/474-Rlab" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 3 Subclassification and Matching | Econometrics of Policy Evaluation" />
  
  <meta name="twitter:description" content="ECON 474 R-lab notes" />
  

<meta name="author" content="Ben Cizek, Alex Costa, Marcelino Guerra, Mingqian Liu" />


<meta name="date" content="2022-01-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inference-review.html"/>
<link rel="next" href="nonlinear-regression.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ECON 474 @UIUC</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="1" data-path="rand-health-insurance-experiment.html"><a href="rand-health-insurance-experiment.html"><i class="fa fa-check"></i><b>1</b> RAND Health Insurance Experiment</a>
<ul>
<li class="chapter" data-level="1.1" data-path="rand-health-insurance-experiment.html"><a href="rand-health-insurance-experiment.html#working-with-.rds-files"><i class="fa fa-check"></i><b>1.1</b> Working with .RDS files</a></li>
<li class="chapter" data-level="1.2" data-path="rand-health-insurance-experiment.html"><a href="rand-health-insurance-experiment.html#summarizing-data"><i class="fa fa-check"></i><b>1.2</b> Summarizing data</a></li>
<li class="chapter" data-level="1.3" data-path="rand-health-insurance-experiment.html"><a href="rand-health-insurance-experiment.html#checking-for-balance"><i class="fa fa-check"></i><b>1.3</b> Checking for Balance</a></li>
<li class="chapter" data-level="1.4" data-path="rand-health-insurance-experiment.html"><a href="rand-health-insurance-experiment.html#results-of-the-experiment"><i class="fa fa-check"></i><b>1.4</b> Results of the Experiment</a></li>
<li class="chapter" data-level="1.5" data-path="rand-health-insurance-experiment.html"><a href="rand-health-insurance-experiment.html#equivalence-of-differences-in-means-and-regression"><i class="fa fa-check"></i><b>1.5</b> Equivalence of Differences in Means and Regression</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="inference-review.html"><a href="inference-review.html"><i class="fa fa-check"></i><b>2</b> Inference Review</a>
<ul>
<li class="chapter" data-level="2.1" data-path="inference-review.html"><a href="inference-review.html#flipping-coins"><i class="fa fa-check"></i><b>2.1</b> Flipping coins</a></li>
<li class="chapter" data-level="2.2" data-path="inference-review.html"><a href="inference-review.html#sample-mean"><i class="fa fa-check"></i><b>2.2</b> Sample mean</a></li>
<li class="chapter" data-level="2.3" data-path="inference-review.html"><a href="inference-review.html#measuring-variability"><i class="fa fa-check"></i><b>2.3</b> Measuring Variability</a></li>
<li class="chapter" data-level="2.4" data-path="inference-review.html"><a href="inference-review.html#central-limit-theorem-clt"><i class="fa fa-check"></i><b>2.4</b> Central Limit Theorem (CLT)</a></li>
<li class="chapter" data-level="2.5" data-path="inference-review.html"><a href="inference-review.html#the-t-statistic-and-the-clt"><i class="fa fa-check"></i><b>2.5</b> The t-Statistic and the CLT</a></li>
<li class="chapter" data-level="2.6" data-path="inference-review.html"><a href="inference-review.html#confidence-interval"><i class="fa fa-check"></i><b>2.6</b> Confidence Interval</a></li>
<li class="chapter" data-level="2.7" data-path="inference-review.html"><a href="inference-review.html#hypothesis-testing"><i class="fa fa-check"></i><b>2.7</b> Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="subclassification-and-matching.html"><a href="subclassification-and-matching.html"><i class="fa fa-check"></i><b>3</b> Subclassification and Matching</a>
<ul>
<li class="chapter" data-level="3.1" data-path="subclassification-and-matching.html"><a href="subclassification-and-matching.html#subclassification-example"><i class="fa fa-check"></i><b>3.1</b> Subclassification Example</a></li>
<li class="chapter" data-level="3.2" data-path="subclassification-and-matching.html"><a href="subclassification-and-matching.html#propensity-score-example"><i class="fa fa-check"></i><b>3.2</b> Propensity Score Example</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="subclassification-and-matching.html"><a href="subclassification-and-matching.html#nearest-neighbor-matching"><i class="fa fa-check"></i><b>3.2.1</b> Nearest-Neighbor Matching</a></li>
<li class="chapter" data-level="3.2.2" data-path="subclassification-and-matching.html"><a href="subclassification-and-matching.html#weighting-on-the-propensity-score"><i class="fa fa-check"></i><b>3.2.2</b> Weighting on the Propensity Score</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="nonlinear-regression.html"><a href="nonlinear-regression.html"><i class="fa fa-check"></i><b>4</b> NonLinear Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="nonlinear-regression.html"><a href="nonlinear-regression.html#generalized-linear-models-glm"><i class="fa fa-check"></i><b>4.1</b> Generalized Linear Models (GLM)</a></li>
<li class="chapter" data-level="4.2" data-path="nonlinear-regression.html"><a href="nonlinear-regression.html#a-taste-of-machine-learning"><i class="fa fa-check"></i><b>4.2</b> A Taste of Machine Learning</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="instrumental-variables.html"><a href="instrumental-variables.html"><i class="fa fa-check"></i><b>5</b> Instrumental Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="instrumental-variables.html"><a href="instrumental-variables.html#preliminaries"><i class="fa fa-check"></i><b>5.1</b> Preliminaries</a></li>
<li class="chapter" data-level="5.2" data-path="instrumental-variables.html"><a href="instrumental-variables.html#ols-results"><i class="fa fa-check"></i><b>5.2</b> OLS results</a></li>
<li class="chapter" data-level="5.3" data-path="instrumental-variables.html"><a href="instrumental-variables.html#wald-estimator"><i class="fa fa-check"></i><b>5.3</b> Wald Estimator</a></li>
<li class="chapter" data-level="5.4" data-path="instrumental-variables.html"><a href="instrumental-variables.html#sls-estimates"><i class="fa fa-check"></i><b>5.4</b> 2SLS Estimates</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="instrumental-variables.html"><a href="instrumental-variables.html#manually-getting-the-coefficient-dont-do-it"><i class="fa fa-check"></i><b>5.4.1</b> Manually getting the coefficient (don’t do it!)</a></li>
<li class="chapter" data-level="5.4.2" data-path="instrumental-variables.html"><a href="instrumental-variables.html#the-correct-way"><i class="fa fa-check"></i><b>5.4.2</b> The correct way</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fixed-effects.html"><a href="fixed-effects.html"><i class="fa fa-check"></i><b>6</b> Fixed Effects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="fixed-effects.html"><a href="fixed-effects.html#preliminaries-1"><i class="fa fa-check"></i><b>6.1</b> Preliminaries</a></li>
<li class="chapter" data-level="6.2" data-path="fixed-effects.html"><a href="fixed-effects.html#between-variation"><i class="fa fa-check"></i><b>6.2</b> Between variation</a></li>
<li class="chapter" data-level="6.3" data-path="fixed-effects.html"><a href="fixed-effects.html#within-variation"><i class="fa fa-check"></i><b>6.3</b> Within variation</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="fixed-effects.html"><a href="fixed-effects.html#regress-the-demeaned-values-of-y_it-on-d_it"><i class="fa fa-check"></i><b>6.3.1</b> Regress the demeaned values of <span class="math inline">\(Y_{it}\)</span> on <span class="math inline">\(D_{it}\)</span></a></li>
<li class="chapter" data-level="6.3.2" data-path="fixed-effects.html"><a href="fixed-effects.html#regress-y_it-on-d_it-and-county-unit-dummies"><i class="fa fa-check"></i><b>6.3.2</b> Regress <span class="math inline">\(Y_{it}\)</span> on <span class="math inline">\(D_{it}\)</span> and county unit dummies</a></li>
<li class="chapter" data-level="6.3.3" data-path="fixed-effects.html"><a href="fixed-effects.html#regress-y_it-on-d_it-with-canned-fixed-effects-routine"><i class="fa fa-check"></i><b>6.3.3</b> Regress <span class="math inline">\(Y_{it}\)</span> on <span class="math inline">\(D_{it}\)</span> with canned fixed effects routine</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="fixed-effects.html"><a href="fixed-effects.html#two-way-fixed-effects"><i class="fa fa-check"></i><b>6.4</b> Two-way fixed effects</a></li>
<li class="chapter" data-level="6.5" data-path="fixed-effects.html"><a href="fixed-effects.html#panel-data-alone-cant-deal-with-simultaneity"><i class="fa fa-check"></i><b>6.5</b> Panel data alone can’t deal with simultaneity</a></li>
<li class="chapter" data-level="6.6" data-path="fixed-effects.html"><a href="fixed-effects.html#intepreting-within-relationships"><i class="fa fa-check"></i><b>6.6</b> Intepreting Within Relationships</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="difference-in-differences.html"><a href="difference-in-differences.html"><i class="fa fa-check"></i><b>7</b> Difference-in-Differences</a>
<ul>
<li class="chapter" data-level="7.1" data-path="difference-in-differences.html"><a href="difference-in-differences.html#line-plots"><i class="fa fa-check"></i><b>7.1</b> Line plots</a></li>
<li class="chapter" data-level="7.2" data-path="difference-in-differences.html"><a href="difference-in-differences.html#difference-in-differences-example-cheng-and-hoekstra-2013"><i class="fa fa-check"></i><b>7.2</b> Difference-in-Differences Example: Cheng and Hoekstra (2013)</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="difference-in-differences.html"><a href="difference-in-differences.html#falsification-tests"><i class="fa fa-check"></i><b>7.2.1</b> Falsification tests</a></li>
<li class="chapter" data-level="7.2.2" data-path="difference-in-differences.html"><a href="difference-in-differences.html#deterrence"><i class="fa fa-check"></i><b>7.2.2</b> Deterrence</a></li>
<li class="chapter" data-level="7.2.3" data-path="difference-in-differences.html"><a href="difference-in-differences.html#homicide-in-florida"><i class="fa fa-check"></i><b>7.2.3</b> Homicide in Florida</a></li>
<li class="chapter" data-level="7.2.4" data-path="difference-in-differences.html"><a href="difference-in-differences.html#multistate-homicide-regression"><i class="fa fa-check"></i><b>7.2.4</b> Multistate Homicide Regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="synthetic-control.html"><a href="synthetic-control.html"><i class="fa fa-check"></i><b>8</b> Synthetic Control</a>
<ul>
<li class="chapter" data-level="8.1" data-path="synthetic-control.html"><a href="synthetic-control.html#preliminaries-2"><i class="fa fa-check"></i><b>8.1</b> Preliminaries</a></li>
<li class="chapter" data-level="8.2" data-path="synthetic-control.html"><a href="synthetic-control.html#the-economic-cost-of-the-1990-german-reunification"><i class="fa fa-check"></i><b>8.2</b> The Economic Cost of the 1990 German Reunification</a></li>
<li class="chapter" data-level="8.3" data-path="synthetic-control.html"><a href="synthetic-control.html#placebo-studies"><i class="fa fa-check"></i><b>8.3</b> Placebo Studies</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Econometrics of Policy Evaluation</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="subclassification-and-matching" class="section level1" number="3">
<h1><span class="header-section-number"> 3</span> Subclassification and Matching</h1>
<div id="subclassification-example" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Subclassification Example</h2>
<p>In this example, we are going to follow <span class="citation"><a href="#ref-cunningham2021causal" role="doc-biblioref">Cunningham</a> (<a href="#ref-cunningham2021causal" role="doc-biblioref">2021</a>)</span> and use a dataset of <em>Titanic</em> passengers. Download the <code>.RDS</code> file <a href="https://github.com/guerramarcelino/PolicyEval/raw/main/Datasets/titanic.RDS">here</a>.</p>
<p>The variables’ description is the following:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-1">Table 3.1: </span>Variables Description
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Definition
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
class
</td>
<td style="text-align:left;width: 12cm; ">
Passenger’s class: 1 if located in the upper decks
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:left;width: 12cm; ">
Passenger’s age: 0 if Child, 1 if Adult
</td>
</tr>
<tr>
<td style="text-align:left;">
sex
</td>
<td style="text-align:left;width: 12cm; ">
Passenger’s gender: 0 if woman, 1 if man
</td>
</tr>
<tr>
<td style="text-align:left;">
survived
</td>
<td style="text-align:left;width: 12cm; ">
1 if survived, 0 otherwise
</td>
</tr>
</tbody>
</table>
<p>Out of 2,201 people among passengers and crew, only 711 survived. It is well known the role that wealth and norms - women and children had priority for lifeboats - played in passengers’ probability of survival, so let’s check whether or not being part of the first class made someone more likely to survive the tragedy. First, let’s compare survival rates between passengers in the upper deck and the others.</p>
<p>Create a dummy variable <code>first_class</code> that takes 1 if <code>class==1</code> and 0 otherwise. Then, use <code>group_by()</code> and <code>summarize()</code> the information calculating the average values of <code>survived</code></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="subclassification-and-matching.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="subclassification-and-matching.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="subclassification-and-matching.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/User/Desktop/474-Rlab/datasets&quot;</span>)</span>
<span id="cb1-4"><a href="subclassification-and-matching.html#cb1-4" aria-hidden="true" tabindex="-1"></a>titanic<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">&quot;titanic.RDS&quot;</span>)</span>
<span id="cb1-5"><a href="subclassification-and-matching.html#cb1-5" aria-hidden="true" tabindex="-1"></a>titanic<span class="sc">$</span>first_class<span class="ot">&lt;-</span><span class="fu">ifelse</span>(titanic<span class="sc">$</span>class<span class="sc">==</span><span class="dv">1</span>,<span class="st">&quot;Upper Deck&quot;</span>,<span class="st">&quot;Lower Decks&quot;</span>)</span>
<span id="cb1-6"><a href="subclassification-and-matching.html#cb1-6" aria-hidden="true" tabindex="-1"></a>titanic<span class="sc">%&gt;%</span><span class="fu">group_by</span>(first_class)<span class="sc">%&gt;%</span><span class="fu">summarize</span>(<span class="at">survival_rate=</span><span class="fu">mean</span>(survived))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   first_class survival_rate
##   &lt;chr&gt;               &lt;dbl&gt;
## 1 Lower Decks         0.271
## 2 Upper Deck          0.625</code></pre>
<p>The naive comparison gives a difference in survival rates of 35.4% for first class seats. That difference is considerable and also statistically significant:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="subclassification-and-matching.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(survived<span class="sc">~</span>first_class, <span class="at">data=</span>titanic)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  survived by first_class
## t = -12.289, df = 423.61, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group Lower Decks and group Upper Deck is not equal to 0
## 95 percent confidence interval:
##  -0.4104198 -0.2972332
## sample estimates:
## mean in group Lower Decks  mean in group Upper Deck 
##                 0.2707889                 0.6246154</code></pre>
<p>However, we also know that women and children were explicitly given priority for boarding the very limited number of lifeboats. Hence, that difference might be biased if those groups - lower and upper deck - are fundamentally different. If women and children are more likely to be seated in the first class, then that difference is driven by social norms.</p>
<p><em>What if we adjust for those two observable confounders (age and gender)?</em> To use subclassification weighting:</p>
<ol style="list-style-type: decimal">
<li><p>Stratify the data into four groups: male children, female children, male adult, female adult</p></li>
<li><p>Calculate the difference in survival probabilities for each group</p></li>
<li><p>Calculate the number of people in the non-first-class groups and divide by the total number of non-first-class population. These are our strata-specific weights</p></li>
<li><p>Calculate the weighted average survival rate using the strata weights</p></li>
</ol>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="subclassification-and-matching.html#cb5-1" aria-hidden="true" tabindex="-1"></a>titanic<span class="sc">%&gt;%</span><span class="fu">group_by</span>(age, sex, first_class)<span class="sc">%&gt;%</span><span class="fu">summarize</span>(<span class="at">outcome=</span><span class="fu">mean</span>(survived), <span class="at">count=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 8 x 5
## # Groups:   age, sex [4]
##          age       sex first_class outcome count
##    &lt;dbl+lbl&gt; &lt;dbl+lbl&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;
## 1 0 [child]  0 [women] Lower Decks   0.614    44
## 2 0 [child]  0 [women] Upper Deck    1         1
## 3 0 [child]  1 [man]   Lower Decks   0.407    59
## 4 0 [child]  1 [man]   Upper Deck    1         5
## 5 1 [adults] 0 [women] Lower Decks   0.626   281
## 6 1 [adults] 0 [women] Upper Deck    0.972   144
## 7 1 [adults] 1 [man]   Lower Decks   0.188  1492
## 8 1 [adults] 1 [man]   Upper Deck    0.326   175</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="subclassification-and-matching.html#cb7-1" aria-hidden="true" tabindex="-1"></a>diff1<span class="ot">=</span><span class="dv">1</span><span class="fl">-0.614</span></span>
<span id="cb7-2"><a href="subclassification-and-matching.html#cb7-2" aria-hidden="true" tabindex="-1"></a>diff2<span class="ot">=</span><span class="dv">1</span><span class="fl">-0.407</span></span>
<span id="cb7-3"><a href="subclassification-and-matching.html#cb7-3" aria-hidden="true" tabindex="-1"></a>diff3<span class="ot">=</span><span class="fl">0.972-0.626</span></span>
<span id="cb7-4"><a href="subclassification-and-matching.html#cb7-4" aria-hidden="true" tabindex="-1"></a>diff4<span class="ot">=</span><span class="fl">0.326-0.188</span></span>
<span id="cb7-5"><a href="subclassification-and-matching.html#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="subclassification-and-matching.html#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="subclassification-and-matching.html#cb7-7" aria-hidden="true" tabindex="-1"></a>weightedATE<span class="ot">=</span><span class="dv">44</span><span class="sc">/</span><span class="dv">1876</span><span class="sc">*</span>diff1<span class="sc">+</span><span class="dv">59</span><span class="sc">/</span><span class="dv">1876</span><span class="sc">*</span>diff2<span class="sc">+</span><span class="dv">281</span><span class="sc">/</span><span class="dv">1876</span><span class="sc">*</span>diff3<span class="sc">+</span><span class="dv">1492</span><span class="sc">/</span><span class="dv">1876</span><span class="sc">*</span>diff4</span>
<span id="cb7-8"><a href="subclassification-and-matching.html#cb7-8" aria-hidden="true" tabindex="-1"></a>weightedATE</span></code></pre></div>
<pre><code>## [1] 0.189282</code></pre>
<p>Using the subclassification weighting scheme, the average treatment effect (ATE) is 18.9%, compared to 35.4% using a simple comparison between first and non-first classes.</p>
</div>
<div id="propensity-score-example" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Propensity Score Example</h2>
<p>In this example, we follow <a href="https://mixtape.scunning.com/matching-and-subclassification.html?panelset7=r-code8&amp;panelset6=r-code7&amp;panelset4=r-code5&amp;panelset5=r-code6#example-the-nsw-job-training-program">Cunningham (2021)</a>. Download the NSW experimental data <a href="https://github.com/guerramarcelino/PolicyEval/raw/main/Datasets/NSW_EXPER.RDS">here</a> and let’s replicate the table we saw in class.</p>
<p>The variables’ description is the following:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-6">Table 3.2: </span>Variables Description
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Definition
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
data_id
</td>
<td style="text-align:left;width: 12cm; ">
Individual’s Identification
</td>
</tr>
<tr>
<td style="text-align:left;">
treat
</td>
<td style="text-align:left;width: 12cm; ">
Treatment: 1 if participated in the Job training, 0 otherwise
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:left;width: 12cm; ">
Age
</td>
</tr>
<tr>
<td style="text-align:left;">
educ
</td>
<td style="text-align:left;width: 12cm; ">
Years of Education
</td>
</tr>
<tr>
<td style="text-align:left;">
black
</td>
<td style="text-align:left;width: 12cm; ">
Race: 1 if Black, 0 otherwise
</td>
</tr>
<tr>
<td style="text-align:left;">
hisp
</td>
<td style="text-align:left;width: 12cm; ">
Race: 1 if Hispanic, 0 otherwise
</td>
</tr>
<tr>
<td style="text-align:left;">
marr
</td>
<td style="text-align:left;width: 12cm; ">
Marital status: 1 if married, 0 otherwise
</td>
</tr>
<tr>
<td style="text-align:left;">
nodegree
</td>
<td style="text-align:left;width: 12cm; ">
1 if participant does not have a degree, 0 otherwise
</td>
</tr>
<tr>
<td style="text-align:left;">
re74
</td>
<td style="text-align:left;width: 12cm; ">
Earnings in 1974 (pre-program)
</td>
</tr>
<tr>
<td style="text-align:left;">
re75
</td>
<td style="text-align:left;width: 12cm; ">
Earnings in 1975 (pre-program)
</td>
</tr>
<tr>
<td style="text-align:left;">
re78
</td>
<td style="text-align:left;width: 12cm; ">
Earnings in 1978 (post-program)
</td>
</tr>
</tbody>
</table>
<p>First, read the <code>.RDS</code> file. Then, summarize the baseline characteristics to check for balance and get the difference in means of earnings in 1978 <code>re78</code>:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="subclassification-and-matching.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb9-2"><a href="subclassification-and-matching.html#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="subclassification-and-matching.html#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/User/Desktop/474-Rlab/datasets&quot;</span>)</span>
<span id="cb9-4"><a href="subclassification-and-matching.html#cb9-4" aria-hidden="true" tabindex="-1"></a>exper_data<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">&quot;NSW_EXPER.RDS&quot;</span>)</span>
<span id="cb9-5"><a href="subclassification-and-matching.html#cb9-5" aria-hidden="true" tabindex="-1"></a>exper_data<span class="sc">%&gt;%</span><span class="fu">group_by</span>(treat)<span class="sc">%&gt;%</span><span class="fu">summarize</span>(<span class="at">Age=</span><span class="fu">mean</span>(age), <span class="at">Education=</span><span class="fu">mean</span>(educ),</span>
<span id="cb9-6"><a href="subclassification-and-matching.html#cb9-6" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Black=</span><span class="fu">mean</span>(black), <span class="at">Hispanic=</span><span class="fu">mean</span>(hisp),</span>
<span id="cb9-7"><a href="subclassification-and-matching.html#cb9-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Married=</span><span class="fu">mean</span>(marr), <span class="st">`</span><span class="at">No degree</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(nodegree),</span>
<span id="cb9-8"><a href="subclassification-and-matching.html#cb9-8" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1974</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re74),</span>
<span id="cb9-9"><a href="subclassification-and-matching.html#cb9-9" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1975</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re75),</span>
<span id="cb9-10"><a href="subclassification-and-matching.html#cb9-10" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1978</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re78),</span>
<span id="cb9-11"><a href="subclassification-and-matching.html#cb9-11" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Number of Observations</span><span class="st">`</span><span class="ot">=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 x 11
##   treat   Age Education Black Hispanic Married `No degree` `Earnings in 1974`
##   &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;              &lt;dbl&gt;
## 1     0  25.1      10.1 0.827   0.108    0.154       0.835              2107.
## 2     1  25.8      10.3 0.843   0.0595   0.189       0.708              2096.
## # ... with 3 more variables: Earnings in 1975 &lt;dbl&gt;, Earnings in 1978 &lt;dbl&gt;,
## #   Number of Observations &lt;int&gt;</code></pre>
<p>Since the NSW was randomized, the independence assumption <span class="math inline">\((Y_{1i}, Y_{0i}) \perp\!\!\!\perp D_{i}\)</span> is satisfied and simple comparisons between means give the average treatment effect (ATE):</p>
<p><span class="math display">\[\frac{1}{N_{Treat}}\sum_{D_{i}=1} Y_{i}-\frac{1}{N_{Control}}\sum_{D_{i}=0}Y_{i} \approx \underbrace{E[Y_{1i}-Y_{0i}]}_{\text{Average Treatment Effect}}\]</span></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="subclassification-and-matching.html#cb11-1" aria-hidden="true" tabindex="-1"></a>mean_treated<span class="ot">&lt;-</span>exper_data<span class="sc">%&gt;%</span><span class="fu">filter</span>(treat<span class="sc">==</span><span class="dv">1</span>)<span class="sc">%&gt;%</span><span class="fu">summarize</span>(<span class="at">avg_earnings78=</span><span class="fu">mean</span>(re78))</span>
<span id="cb11-2"><a href="subclassification-and-matching.html#cb11-2" aria-hidden="true" tabindex="-1"></a>mean_control<span class="ot">&lt;-</span>exper_data<span class="sc">%&gt;%</span><span class="fu">filter</span>(treat<span class="sc">==</span><span class="dv">0</span>)<span class="sc">%&gt;%</span><span class="fu">summarize</span>(<span class="at">avg_earnings78=</span><span class="fu">mean</span>(re78))</span>
<span id="cb11-3"><a href="subclassification-and-matching.html#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="subclassification-and-matching.html#cb11-4" aria-hidden="true" tabindex="-1"></a>mean_treated<span class="sc">-</span>mean_control</span></code></pre></div>
<pre><code>##   avg_earnings78
## 1       1794.342</code></pre>
<p>The causal effect of the NSW job-training program is $1,794.</p>
<p>What if we replace the experimental control group with a random sample of Americans from the <code>Current Population Survey</code>? Download this data <a href="https://github.com/guerramarcelino/PolicyEval/raw/main/Datasets/NSW_NE.RDS">here</a> and let’s see how it goes.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="subclassification-and-matching.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/User/Desktop/474-Rlab/datasets&quot;</span>)</span>
<span id="cb13-2"><a href="subclassification-and-matching.html#cb13-2" aria-hidden="true" tabindex="-1"></a>nonexper_data<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">&quot;NSW_NE.RDS&quot;</span>)</span>
<span id="cb13-3"><a href="subclassification-and-matching.html#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="subclassification-and-matching.html#cb13-4" aria-hidden="true" tabindex="-1"></a>nonexper_data<span class="sc">%&gt;%</span><span class="fu">group_by</span>(treat)<span class="sc">%&gt;%</span><span class="fu">summarize</span>(<span class="at">Age=</span><span class="fu">mean</span>(age), <span class="at">Education=</span><span class="fu">mean</span>(educ),</span>
<span id="cb13-5"><a href="subclassification-and-matching.html#cb13-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Black=</span><span class="fu">mean</span>(black), <span class="at">Hispanic=</span><span class="fu">mean</span>(hisp),</span>
<span id="cb13-6"><a href="subclassification-and-matching.html#cb13-6" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Married=</span><span class="fu">mean</span>(marr), <span class="st">`</span><span class="at">No degree</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(nodegree),</span>
<span id="cb13-7"><a href="subclassification-and-matching.html#cb13-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1974</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re74),</span>
<span id="cb13-8"><a href="subclassification-and-matching.html#cb13-8" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1975</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re75),</span>
<span id="cb13-9"><a href="subclassification-and-matching.html#cb13-9" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1978</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re78),</span>
<span id="cb13-10"><a href="subclassification-and-matching.html#cb13-10" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Number of Observations</span><span class="st">`</span><span class="ot">=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 x 11
##   treat   Age Education  Black Hispanic Married `No degree` `Earnings in 1974`
##   &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;              &lt;dbl&gt;
## 1     0  33.2      12.0 0.0735   0.0720   0.712       0.296             14017.
## 2     1  25.8      10.3 0.843    0.0595   0.189       0.708              2096.
## # ... with 3 more variables: Earnings in 1975 &lt;dbl&gt;, Earnings in 1978 &lt;dbl&gt;,
## #   Number of Observations &lt;int&gt;</code></pre>
<p>As you can see, the NSW participants are younger, less educated, more black, less likely to be married, more likely to have no degree, among others - those two groups are fundamentally different.</p>
<div id="nearest-neighbor-matching" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Nearest-Neighbor Matching</h3>
<p>One possibility is to use a matched sample that better approximates the NSW participants using propensity scores - the conditional probability of receiving the treatment given covariate values (in this case, education, age, past earnings, etc.). To get those estimated probabilities, we can use a logit regression:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="subclassification-and-matching.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the glm() function with</span></span>
<span id="cb15-2"><a href="subclassification-and-matching.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the family = binomial(link = &#39;logit&#39;) option</span></span>
<span id="cb15-3"><a href="subclassification-and-matching.html#cb15-3" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="ot">&lt;-</span> <span class="fu">glm</span>( treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span> marr <span class="sc">+</span> nodegree <span class="sc">+</span> black <span class="sc">+</span></span>
<span id="cb15-4"><a href="subclassification-and-matching.html#cb15-4" aria-hidden="true" tabindex="-1"></a>              hisp <span class="sc">+</span> re74 <span class="sc">+</span> re75, <span class="at">data =</span> nonexper_data,</span>
<span id="cb15-5"><a href="subclassification-and-matching.html#cb15-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>))</span></code></pre></div>
<p>And get its fitted values:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="subclassification-and-matching.html#cb16-1" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">prop_score =</span> <span class="fu">predict</span>(logit_reg, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>),</span>
<span id="cb16-2"><a href="subclassification-and-matching.html#cb16-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">job_training =</span> logit_reg<span class="sc">$</span>model<span class="sc">$</span>treat)</span>
<span id="cb16-3"><a href="subclassification-and-matching.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co">#View(probs)</span></span>
<span id="cb16-4"><a href="subclassification-and-matching.html#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(probs,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   prop_score job_training
## 1 0.24751114            1
## 2 0.07257909            1
## 3 0.25039795            1
## 4 0.47895432            1
## 5 0.44753066            1</code></pre>
<p>One of the assumptions for matching is the existence of <strong>common support</strong>: there must be units in both the treatment and control groups for any probability. In other words, common support ensures enough overlap in the characteristics of treated and control units to find suitable matches.</p>
<p>You can look at the distributions of the propensity score in the treated and control groups:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="subclassification-and-matching.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb18-2"><a href="subclassification-and-matching.html#cb18-2" aria-hidden="true" tabindex="-1"></a>hist1<span class="ot">&lt;-</span>probs  <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="subclassification-and-matching.html#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(job_training <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="subclassification-and-matching.html#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb18-5"><a href="subclassification-and-matching.html#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> prop_score))<span class="sc">+</span></span>
<span id="cb18-6"><a href="subclassification-and-matching.html#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Probability of getting Job-training: control&quot;</span>)<span class="sc">+</span></span>
<span id="cb18-7"><a href="subclassification-and-matching.html#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb18-8"><a href="subclassification-and-matching.html#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="subclassification-and-matching.html#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="subclassification-and-matching.html#cb18-10" aria-hidden="true" tabindex="-1"></a>hist2<span class="ot">&lt;-</span>probs  <span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a href="subclassification-and-matching.html#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(job_training <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-12"><a href="subclassification-and-matching.html#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb18-13"><a href="subclassification-and-matching.html#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> prop_score))<span class="sc">+</span></span>
<span id="cb18-14"><a href="subclassification-and-matching.html#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Probability of getting Job-training: treated&quot;</span>)<span class="sc">+</span></span>
<span id="cb18-15"><a href="subclassification-and-matching.html#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb18-16"><a href="subclassification-and-matching.html#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="subclassification-and-matching.html#cb18-17" aria-hidden="true" tabindex="-1"></a>hist1<span class="sc">+</span>hist2</span></code></pre></div>
<p><img src="images/unnamed-chunk-12-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>It does not look good! The characteristics of individuals in the treatment group are scarce in the CPS sample we are using as a non-experimental control group.</p>
<p>A simple method for estimating the average treatment effect of the NSW training is to restrict the sample finding pairs of observations with very similar propensity scores but with different treatment statuses:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="subclassification-and-matching.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span>
<span id="cb19-2"><a href="subclassification-and-matching.html#cb19-2" aria-hidden="true" tabindex="-1"></a>m_out <span class="ot">&lt;-</span> <span class="fu">matchit</span>(treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span></span>
<span id="cb19-3"><a href="subclassification-and-matching.html#cb19-3" aria-hidden="true" tabindex="-1"></a>                    marr <span class="sc">+</span> nodegree <span class="sc">+</span></span>
<span id="cb19-4"><a href="subclassification-and-matching.html#cb19-4" aria-hidden="true" tabindex="-1"></a>                   black <span class="sc">+</span> hisp <span class="sc">+</span> re74 <span class="sc">+</span> re75,</span>
<span id="cb19-5"><a href="subclassification-and-matching.html#cb19-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> nonexper_data, <span class="at">method =</span> <span class="st">&quot;nearest&quot;</span>,</span>
<span id="cb19-6"><a href="subclassification-and-matching.html#cb19-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">distance =</span> <span class="st">&quot;logit&quot;</span>)</span>
<span id="cb19-7"><a href="subclassification-and-matching.html#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="subclassification-and-matching.html#cb19-8" aria-hidden="true" tabindex="-1"></a>m_data <span class="ot">&lt;-</span> <span class="fu">match.data</span>(m_out)</span>
<span id="cb19-9"><a href="subclassification-and-matching.html#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co">#View(m_data)</span></span>
<span id="cb19-10"><a href="subclassification-and-matching.html#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(m_data)</span></code></pre></div>
<pre><code>## [1] 370  14</code></pre>
<p>The matched sample has 370 individuals: 185 in the treatment group and 185 in the control group. You might want to see if there is indeed a balance between covariates in the new dataset:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="subclassification-and-matching.html#cb21-1" aria-hidden="true" tabindex="-1"></a>m_data<span class="sc">%&gt;%</span><span class="fu">group_by</span>(treat)<span class="sc">%&gt;%</span><span class="fu">summarize</span>(<span class="at">Age=</span><span class="fu">mean</span>(age), <span class="at">Education=</span><span class="fu">mean</span>(educ),</span>
<span id="cb21-2"><a href="subclassification-and-matching.html#cb21-2" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Black=</span><span class="fu">mean</span>(black), <span class="at">Hispanic=</span><span class="fu">mean</span>(hisp),</span>
<span id="cb21-3"><a href="subclassification-and-matching.html#cb21-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Married=</span><span class="fu">mean</span>(marr), <span class="st">`</span><span class="at">No degree</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(nodegree),</span>
<span id="cb21-4"><a href="subclassification-and-matching.html#cb21-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1974</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re74),</span>
<span id="cb21-5"><a href="subclassification-and-matching.html#cb21-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1975</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re75),</span>
<span id="cb21-6"><a href="subclassification-and-matching.html#cb21-6" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Earnings in 1978</span><span class="st">`</span><span class="ot">=</span><span class="fu">mean</span>(re78),</span>
<span id="cb21-7"><a href="subclassification-and-matching.html#cb21-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Number of Observations</span><span class="st">`</span><span class="ot">=</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 x 11
##   treat   Age Education Black Hispanic Married `No degree` `Earnings in 1974`
##   &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;              &lt;dbl&gt;
## 1     0  23.8      10.4 0.827   0.0432   0.135       0.681              1905.
## 2     1  25.8      10.3 0.843   0.0595   0.189       0.708              2096.
## # ... with 3 more variables: Earnings in 1975 &lt;dbl&gt;, Earnings in 1978 &lt;dbl&gt;,
## #   Number of Observations &lt;int&gt;</code></pre>
<p>You can also run <code>t.test()</code> and see if the differences are statistically significant (they shouldn’t be). To get the average treatment effect, you can calculate the difference in 1978 average earnings between the treatment and control group or run a regression:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="subclassification-and-matching.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb23-2"><a href="subclassification-and-matching.html#cb23-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">feols</span>(re78<span class="sc">~</span>treat, <span class="at">data=</span>m_data, <span class="at">se=</span><span class="st">&quot;hetero&quot;</span>)</span>
<span id="cb23-3"><a href="subclassification-and-matching.html#cb23-3" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span><span class="fu">feols</span>(re78<span class="sc">~</span>treat<span class="sc">+</span>age<span class="sc">+</span>educ<span class="sc">+</span>black<span class="sc">+</span>hisp<span class="sc">+</span>marr<span class="sc">+</span>nodegree<span class="sc">+</span>re74<span class="sc">+</span>re75, <span class="at">data=</span>m_data, <span class="at">se=</span><span class="st">&quot;hetero&quot;</span>)</span>
<span id="cb23-4"><a href="subclassification-and-matching.html#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="subclassification-and-matching.html#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(reg1, reg2, <span class="at">signifCode =</span> <span class="fu">c</span>(<span class="st">&quot;***&quot;</span><span class="ot">=</span><span class="fl">0.01</span>, <span class="st">&quot;**&quot;</span><span class="ot">=</span><span class="fl">0.05</span>, <span class="st">&quot;*&quot;</span><span class="ot">=</span><span class="fl">0.10</span>))</span></code></pre></div>
<pre><code>##                               reg1              reg2
## Dependent Var.:               re78              re78
##                                                     
## (Intercept)     4,586.9*** (423.8)   199.9 (3,716.3)
## treat            1,762.2** (717.1) 1,678.8** (697.5)
## age                                   -6.903 (43.98)
## educ                                  428.4* (231.7)
## black                               -689.8 (1,050.8)
## hisp                               1,152.2 (1,872.4)
## marr                                 377.2 (1,089.4)
## nodegree                             271.5 (1,162.5)
## re74                                -0.0108 (0.1801)
## re75                                0.3189* (0.1764)
## _______________ __________________ _________________
## S.E. type       Heteroskedas.-rob. Heteroskeda.-rob.
## Observations                   370               370
## R2                         0.01615           0.05328
## Adj. R2                    0.01347           0.02961</code></pre>
</div>
<div id="weighting-on-the-propensity-score" class="section level3" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Weighting on the Propensity Score</h3>
<p>Besides nearest-neighbor matching, there are several other ways to get average treatment effects using the estimated propensity score. Assuming the CIA holds, one can use the individuals’ propensity score to weigh their outcomes.</p>
<p>The first step is to generate the propensity scores using the logit regression:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="subclassification-and-matching.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/User/Desktop/474-Rlab/datasets&quot;</span>)</span>
<span id="cb25-2"><a href="subclassification-and-matching.html#cb25-2" aria-hidden="true" tabindex="-1"></a>nonexper_data<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">&quot;NSW_NE.RDS&quot;</span>)</span>
<span id="cb25-3"><a href="subclassification-and-matching.html#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="subclassification-and-matching.html#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Logit model to predict probability of treatment</span></span>
<span id="cb25-5"><a href="subclassification-and-matching.html#cb25-5" aria-hidden="true" tabindex="-1"></a>logit_reg <span class="ot">&lt;-</span> <span class="fu">glm</span>( treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span> marr <span class="sc">+</span> nodegree <span class="sc">+</span> black <span class="sc">+</span></span>
<span id="cb25-6"><a href="subclassification-and-matching.html#cb25-6" aria-hidden="true" tabindex="-1"></a>              hisp <span class="sc">+</span> re74 <span class="sc">+</span> re75, <span class="at">data =</span> nonexper_data,</span>
<span id="cb25-7"><a href="subclassification-and-matching.html#cb25-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>))</span>
<span id="cb25-8"><a href="subclassification-and-matching.html#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="subclassification-and-matching.html#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate propensity scores</span></span>
<span id="cb25-10"><a href="subclassification-and-matching.html#cb25-10" aria-hidden="true" tabindex="-1"></a>nonexper_data<span class="sc">$</span>prop_scores<span class="ot">&lt;-</span>logit_reg<span class="sc">$</span>fitted.values</span></code></pre></div>
<p>After that, trim the data using a good rule of thumb: we keep observations on the interval [0.1,0.9]. Then, calculate the inverse probability weights (IPW) following this formula:</p>
<p><span class="math display">\[\frac{Treatment}{Propensity}-\frac{1-Treatment}{1-Propensity}\]</span></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="subclassification-and-matching.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Trimming the data</span></span>
<span id="cb26-2"><a href="subclassification-and-matching.html#cb26-2" aria-hidden="true" tabindex="-1"></a>nonexper_data<span class="ot">&lt;-</span>nonexper_data<span class="sc">%&gt;%</span><span class="fu">filter</span>(prop_scores<span class="sc">&gt;=</span>.<span class="dv">1</span> <span class="sc">&amp;</span>prop_scores<span class="sc">&lt;=</span>.<span class="dv">9</span> )</span>
<span id="cb26-3"><a href="subclassification-and-matching.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Generating the IPW</span></span>
<span id="cb26-4"><a href="subclassification-and-matching.html#cb26-4" aria-hidden="true" tabindex="-1"></a>nonexper_data<span class="ot">&lt;-</span>nonexper_data <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="subclassification-and-matching.html#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ipw =</span> (treat <span class="sc">/</span> prop_scores) <span class="sc">+</span> ((<span class="dv">1</span> <span class="sc">-</span> treat) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> prop_scores)))</span></code></pre></div>
<p>Finally, run a weighted regression using <code>ipw</code> as weights:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="subclassification-and-matching.html#cb27-1" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(re78 <span class="sc">~</span> treat, <span class="at">data =</span> nonexper_data,  <span class="at">se=</span><span class="st">&quot;hetero&quot;</span>,  <span class="at">weights =</span> nonexper_data<span class="sc">$</span>ipw)</span>
<span id="cb27-2"><a href="subclassification-and-matching.html#cb27-2" aria-hidden="true" tabindex="-1"></a>reg4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(re78 <span class="sc">~</span> treat<span class="sc">+</span>age<span class="sc">+</span>educ<span class="sc">+</span>black<span class="sc">+</span>hisp<span class="sc">+</span>marr<span class="sc">+</span>nodegree<span class="sc">+</span>re74<span class="sc">+</span>re75, <span class="at">data =</span> nonexper_data,  <span class="at">se=</span><span class="st">&quot;hetero&quot;</span>,  <span class="at">weights =</span> nonexper_data<span class="sc">$</span>ipw)</span>
<span id="cb27-3"><a href="subclassification-and-matching.html#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(reg3,reg4,<span class="at">signifCode =</span> <span class="fu">c</span>(<span class="st">&quot;***&quot;</span><span class="ot">=</span><span class="fl">0.01</span>, <span class="st">&quot;**&quot;</span><span class="ot">=</span><span class="fl">0.05</span>, <span class="st">&quot;*&quot;</span><span class="ot">=</span><span class="fl">0.10</span>))</span></code></pre></div>
<pre><code>##                               reg3              reg4
## Dependent Var.:               re78              re78
##                                                     
## (Intercept)     4,425.6*** (312.3) 2,542.1 (2,937.0)
## treat            1,713.8** (732.8) 1,686.3** (740.4)
## age                                   -42.71 (36.13)
## educ                                  299.6* (181.8)
## marr                                 74.42 (1,125.0)
## nodegree                            -448.5 (1,104.9)
## re74                                -0.1361 (0.1192)
## re75                                 0.3328 (0.2175)
## _______________ __________________ _________________
## S.E. type       Heteroskedas.-rob. Heteroskeda.-rob.
## Observations                   504               504
## R2                         0.01541           0.04135
## Adj. R2                    0.01345           0.02782</code></pre>
<p>The average treatment effect using IPW is $1,686-1,714, close to the actual causal effect we got from the randomized trial.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-cunningham2021causal" class="csl-entry">
Cunningham, Scott. 2021. <em>Causal Inference</em>. Yale University Press.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inference-review.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nonlinear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-Matching.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
